name: techFeed
description: Simple app to read tech related news.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:

  webfeed: ^0.7.0

  flutter:
    sdk: flutter

  http: ^0.13.4
  url_launcher: ^6.0.18
  html: ^0.15.0
  shared_preferences: ^2.0.12

dev_dependencies:


  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  lint: ^1.0.0
  
flutter:
  uses-material-design: true